name: Scrape New CodeWars Solved Katas

on:
  workflow_dispatch:
  schedule:
    - cron: "55 19 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 lsof libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libxshmfence1

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          CODEWARS_EMAIL: ${{ secrets.CODEWARS_EMAIL }}
          CODEWARS_PASSWORD: ${{ secrets.CODEWARS_PASSWORD }}
        run: node index.js

      - name: Set Today's Date
        run: echo "TODAY=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Add katas solved on ${{ env.TODAY }}"
          add: .
