name: Scrape New CodeWars Solved Katas

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *" # 12:00 AM IST

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 lsof

      - name: Install Google Chrome
        run: npx @puppeteer/browsers install chrome@stable

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "v22.5.1"

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          CODEWARS_EMAIL: ${{ secrets.CODEWARS_EMAIL }}
          CODEWARS_PASSWORD: ${{ secrets.CODEWARS_PASSWORD }}
        run: node index.js

      - name: Set Today's Date
        run: echo "TODAY=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Add katas solved on ${{ env.TODAY }}"
          add: recording.mp4
